<?php
/**
 * Desafio Alpha - AlphaCore
 * 
 * LICENÇA:
 * 
 * Este software é distribuído sob a licença GNU General Public License - Versão 3. 
 * O conteúdo desta licença está disponível no arquivo LICENSE.txt e nos endereços web 
 * http://doc.desafioalpha.com.br/legal e http://www.gnu.org/licenses/gpl.html
 * 
 * Qualquer dúvida sobre este arquivo fonte e como usá-lo refira-se à 
 * documentação anexada à este pacote de software ou envie um email 
 * para dev@desafioalpha.com.br
 * 
 * ESTE SOFTWARE É DISPONIBILIZADO 'NA FORMA COMO ESTÁ', O AUTOR NÃO OFERECE 
 * NENHUMA GARANTIA, EXPLÍCITA OU IMPLÍCITA, SOBRE PRECISÃO E CONFIABILIDADE.
 * SINTA-SE LIVRE PARA VER, MODIFICAR E REDISTRIBUIR, SOB AS CONDIÇÕES DA 
 * LICENÇA APLICADA. 
 *
 * @category     Desafio Alpha
 * @package      DA_Admin
 * @subpackage   Questions
 * @file         database.phtml
 * @encoding     UTF-8
 * 
 * @author       Desafio Alpha Dev Team <dev@desafioalpha.com.br>
 * @copyright    Copyright (c) 2007-2012 Desafio Alpha (http://desafioalpha.com.br)
 * @license      http://doc.desafioalpha.com.br/legal/gplv3 GPLv3
 */
?>
<div id="questions_info">Existem <?php echo $this->questionCount ?> desafios cadastrados</div>
<div id="search_bar">
    <a href="#" class="last selected" rel="5">Últimos 5</a>
    <a href="#" class="last" rel="0">Todos</a>
<b></b>
<span>Marcados para:</span>
    <a href="#" class="status" rel="0">Final</a>
    <a href="#" class="status" rel="1">Revisão</a>
    <a href="#" class="status" rel="2">Exclusão</a>
    <a href="#" class="new_questions">Novos</a>
</div>
<div id="question_list"></div>
<div id="question_list_new"></div>
<div id="question_template" class="hidden">
    <div class="question">
        <a class="header" href="#">
            <span class="flag"></span>
            <input type="hidden" class="question_id" value="">
            <span class="description">Desafio ID: <span class="question_id"></span></span>
            <span class="username">Por <span class="edit_username"></span></span>
            <span class="time">Modificado em <span class="edit_lasttime"></span></span>
        </a>
        <button class="reset"><span>Redefinir...</span></button>
        <div class="question_load"></div>
    </div>
</div>