<?php
/**
 * Desafio Alpha - AlphaCore
 * 
 * LICENÇA:
 * 
 * Este software é distribuído sob a licença GNU General Public License - Versão 3. 
 * O conteúdo desta licença está disponível no arquivo LICENSE.txt e nos endereços web 
 * http://doc.desafioalpha.com.br/legal e http://www.gnu.org/licenses/gpl.html
 * 
 * Qualquer dúvida sobre este arquivo fonte e como usá-lo refira-se à 
 * documentação anexada à este pacote de software ou envie um email 
 * para dev@desafioalpha.com.br
 * 
 * ESTE SOFTWARE É DISPONIBILIZADO 'NA FORMA COMO ESTÁ', O AUTOR NÃO OFERECE 
 * NENHUMA GARANTIA, EXPLÍCITA OU IMPLÍCITA, SOBRE PRECISÃO E CONFIABILIDADE.
 * SINTA-SE LIVRE PARA VER, MODIFICAR E REDISTRIBUIR, SOB AS CONDIÇÕES DA 
 * LICENÇA APLICADA. 
 *
 * @category     Desafio Alpha
 * @package      DA_
 * @file         header.phtml
 * @encoding     UTF-8
 * 
 * @author       Desafio Alpha Dev Team <dev@desafioalpha.com.br>
 * @copyright    Copyright (c) 2007-2012 Desafio Alpha (http://desafioalpha.com.br)
 * @license      http://doc.desafioalpha.com.br/legal/gplv3 GPLv3
 */
?>
<header>

    <div id="pub_header">
        <div id="pub_header_main">
            <div id="pub_header_logo">
                <a href="/"></a>
            </div>
            <?php if(!$this->identity) { ?>
            <a href="/index/login" class="button"><span>Entrar</span></a>
            <?php }else{ ?>
            <a href="/index/logout" class="button"><span>Sair</span></a>
            <?php }?>
        </div>
        <nav>
            <div id="pub_nav" class="nav">
            <?php echo $this->nav ?>
        </div>
        <?php $subMenu = $this->nav->setMinDepth(1)
                               ->setMaxDepth(1)
                               ->setRenderParents(false)
                               ->setOnlyActiveBranch(true) 
                               ->render()
        ?>
        
            <?php if($subMenu) { ?><div id="pub_subnav" class="nav"><?php echo $subMenu ?></div><?php } ?>
        </nav>
    </div>

</header>
