<?php
/**
 * Desafio Alpha - AlphaCore
 * 
 * LICENÇA:
 * 
 * Este software é distribuído sob a licença GNU General Public License - Versão 3. 
 * O conteúdo desta licença está disponível no arquivo LICENSE.txt e nos endereços web 
 * http://doc.desafioalpha.com.br/legal e http://www.gnu.org/licenses/gpl.html
 * 
 * Qualquer dúvida sobre este arquivo fonte e como usá-lo refira-se à 
 * documentação anexada à este pacote de software ou envie um email 
 * para dev@desafioalpha.com.br
 * 
 * ESTE SOFTWARE É DISPONIBILIZADO 'NA FORMA COMO ESTÁ', O AUTOR NÃO OFERECE 
 * NENHUMA GARANTIA, EXPLÍCITA OU IMPLÍCITA, SOBRE PRECISÃO E CONFIABILIDADE.
 * SINTA-SE LIVRE PARA VER, MODIFICAR E REDISTRIBUIR, SOB AS CONDIÇÕES DA 
 * LICENÇA APLICADA. 
 *
 * @category     Desafio Alpha
 * @package      DA_Admin
 * @file         menu.phtml
 * @encoding     UTF-8
 * 
 * @author       Desafio Alpha Dev Team <dev@desafioalpha.com.br>
 * @copyright    Copyright (c) 2007-2012 Desafio Alpha (http://desafioalpha.com.br)
 * @license      http://doc.desafioalpha.com.br/legal/gplv3 GPLv3
 */

/**
 * Partial para renderização personalizada do menu para o plugin jquery.fisheye
 */
$html = array();

$page = $this->container->findBy('active', true); // Obtém a página ativa

if(!empty($page->pages)){
    
    // Monta o container para o menu personalizado
    $html[] = '<div id="dock"><div class="dock_container">';
    
    foreach ($page->pages as $subpage) 
    {
        /* Lista as subpáginas que são visíveis para o cliente atual */
        if($subpage->isVisible() && $this->navigation()->accept($subpage) && $href = $subpage->getHref()){
            
            ($title = $subpage->getTitle()) || $title = $subpage->getLabel(); // Usa o title, se informado, caso contrário usa a label
            
            $html[] = "<a href=\"$href\" title=\"$title\">";
            $html[] = '<span></span>';
            $html[] = '<img src="'.STATIC_URL . '/media/icons/menu/'. $subpage->__get('icon').'.png" alt="">';
            $html[] = "</a>";
            
        }
    }
    
    $html[] = '</div></div><div id="menu_detail"></div>';
}

echo join(PHP_EOL, $html);
